### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by kohonda** [SplatLearn/SplatGym#1]
Hi! Thank you for sharing the code for the interesting project! 
When I tried running it according to the README, I got some errors and questions.

1. When I run `pip install -r src/requirements.txt`, I got the following error:
```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/ktietz/src/ci/backcall_1611930011877/work'
```
It seems that the requirements.txt file includes links to some local files.

2. I noticed in the requirements.txt that two different CUDA versions are referenced. For example, PyTorch uses CUDA 11.8 (torch==2.1.2+cu118), while cuBLAS  requires 12.1 (nvidia-cublas-cu12==12.1.3.1). Could you provide which version of CUDA should we use?
Could you also provide details on the operating system and Python version for running the code?

Lastly, if available, Dockerfile for this code would be incredibly helpful!

**Comment by LiyouZhou** [comment]
@kohonda Thank you for trying out the stack, apologies for the bug in the instructions and build system I have fixed the issue in #2 and created a pre-build docker image at [hub.docker.com/r/liyouzhou/splat_gym](https://hub.docker.com/r/liyouzhou/splat_gym). Please try it out and feel free to reach out if there are further issues.

**Comment by kohonda** [comment]
@LiyouZhou Thank you for providing the Docker environment! I am currently trying to run training with my own data, but I am struggling to get it working due to issues like not being able to find pointcloud_setting.json and differences in the expected directory structure for the data. If possible, could you provide the sample data you are using or recommend a directory structure for the data?

**Comment by LiyouZhou** [comment]
@kohonda I think it is a good suggestion, I will look into providing sample data and instructions in the next few days.
