### ISSUE TITLE
Provide sample data and instructions

### ISSUE THREAD

**Issue by LiyouZhou** [SplatLearn/SplatGym#3]
@LiyouZhou Thank you for providing the Docker environment! I am currently trying to run training with my own data, but I am struggling to get it working due to issues like not being able to find pointcloud_setting.json and differences in the expected directory structure for the data. If possible, could you provide the sample data you are using or recommend a directory structure for the data?

_Originally posted by @kohonda in https://github.com/SplatLearn/SplatGym/issues/1#issuecomment-2475874872_

**Comment by LiyouZhou** [comment]
@kohonda I have added an example [here](https://github.com/SplatLearn/SplatGym/tree/main/examples/poster_env). Please let me know if it can be further improved.

**Comment by kohonda** [comment]
@LiyouZhou Cool! Thank you! I will check it later!
